# This file is used for deploying to app engine (to serve up these static files)
application: droneshare
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  upload: /index.html
  static_files: index.html

- url: /(.*)
  static_files: \1
  upload: .*
